name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]     # change to your feature branch if needed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Make the site artifact from the frontend folder
      - name: Prepare Pages artifact
        run: |
          mkdir _site
          cp -R frontend/* _site/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
