name: Deploy frontend to GitHub Pages

on:
  push:
    branches: ["**"]     # deploy on any branch push
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare site from frontend/
        run: |
          test -d frontend || (echo "frontend/ not found" && exit 1)
          mkdir _site
          cp -R frontend/* _site/
          echo "branch=${GITHUB_REF_NAME}" > _site/version.txt
          echo "sha=${GITHUB_SHA}" >> _site/version.txt

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
